<a href="https://colab.research.google.com/github/abrhamadam/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy
# numpy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. NumPy is widely used for numerical computations and data analysis in Python, and it serves as the foundation for many other scientific computing libraries in the Python ecosystem.

In [1]:
list1= [1,2,3,4,5,6,6]
list1


[1, 2, 3, 4, 5, 6, 6]

In [2]:
list2=["abrham", "alex",  list1, 8]
print(list2)

['abrham', 'alex', [1, 2, 3, 4, 5, 6, 6], 8]


# NumPy arrays are more memory efficient compared to Python lists, especially when dealing with large datasets, as they store elements in a contiguous block of memory.

In [3]:
import numpy as np
np1= np.array([0,1,2,3,4,5,6,7,8,9])
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np1.shape

(10,)

In [5]:
np2= np.arange(10)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np3= np.arange(1,20,3)
print("np3=" , np3)
np4= np.zeros(10)
print("np4="  ,np4)

np3= [ 1  4  7 10 13 16 19]
np4= [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
np5= np.zeros((1,10))
print("np5=" , np5)
np6= np.full((10),2)
print("np6="  ,np6)

np5= [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
np6= [2 2 2 2 2 2 2 2 2 2]


In [8]:
np7=np.full((2,10),6)
print(np7)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [9]:
my_list=[1,2,3,4,5]
np8=np.array(my_list)
np8

array([1, 2, 3, 4, 5])

### slicing numpy array

In [13]:

np8= np.array([0,1,2,3,4,5,6,7,8,9])
print(np8[1:5])

[1 2 3 4]


In [14]:
print(np8[2:])

[2 3 4 5 6 7 8 9]


In [15]:
print(np8[7:])

[7 8 9]


## Numpy Universal function

In [17]:
import numpy as np

# Mathematical functions
np9 = np.array([0, 1, 2, 3])
print(np.sin(np9))  # Compute sine of each element
print(np.exp(np9))  # Compute exponential of each element

# Arithmetic operations
np10 = np.array([1, 2, 3, 4])
np11 = np.array([5, 6, 7, 8])
# addition
print(np.add(np10, np11))
 #  subtraction
print(np.subtract(np10, np11))


[0.         0.84147098 0.90929743 0.14112001]
[ 1.          2.71828183  7.3890561  20.08553692]
[ 6  8 10 12]
[-4 -4 -4 -4]


## Numpy array copy vs view

# a/ copy

In [19]:
#copy of array
np12 = np.array([1, 2, 3])
 # Creating a copy
np13 = np12.copy()
# Modifying the copy
np13[0] = 100
print(np12)
print(np13)


[1 2 3]
[100   2   3]


## b/ view

In [20]:
np14 = np.array([1, 2, 3])
np15 = np14.view()  # Creating a view
np15[0] = 100  # Modifying the view
print(np14)  # Output: [100 2 3]
print(np15)  # Output: [100 2 3]


[100   2   3]
[100   2   3]


## Numpy shape and reshaping

In [21]:
np16 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np16)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
np16.shape

(12,)

In [27]:
np17 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(np17)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [28]:
np17.shape

(2, 6)

In [29]:
np18= np16.reshape(2,3,2)
np18

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

## for iterating through numpy array

In [30]:
np19 = np.array([1, 2, 3, 4, 5])

# Using a for loop to iterate through the array
for element in np19:
    print(element)


1
2
3
4
5


In [31]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Using nested loops to iterate through the 2D array
for row in arr_2d:
    for element in row:
        print(element)


1
2
3
4
5
6
7
8
9


In [32]:
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])

# Using nested loops to iterate through the 3D array
for matrix in arr_3d:
    for row in matrix:
        for element in row:
            print(element)


1
2
3
4
5
6
7
8
9
10
11
12


## sorting numpy array

In [34]:
np20 = np.array([3, 1, 2, 5, 4])

sorted_arr = np.sort(np20)
print(sorted_arr)  # sorted: [1 2 3 4 5]


np20.sort()
print(np20)  # sorted: [1 2 3 4 5]


[1 2 3 4 5]
[1 2 3 4 5]


## Searching through numpy array

In [36]:


np21 = np.array([1, 2, 3, 4, 5])


indices = np.where(np21 == 3)
print(indices)  #search: (array([2]),)

valor = np21[indices[0][0]]
print(valor)  # Search: 3


(array([2]),)
3
